# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [5]:
# your code here
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x000001CEF0D492E0>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1
a = np.random.random((2,3,5))


array([[[0.07072139, 0.72902613, 0.30102606, 0.17852937, 0.29223761],
        [0.9050767 , 0.52327413, 0.77688575, 0.82430772, 0.03290923],
        [0.68433149, 0.53126271, 0.40118318, 0.12979977, 0.79356757]],

       [[0.74760867, 0.57134778, 0.91224543, 0.71890306, 0.63823787],
        [0.14462357, 0.84584131, 0.44899149, 0.6808421 , 0.11948021],
        [0.50097376, 0.87840702, 0.17547447, 0.62221978, 0.82434951]]])

In [8]:
# Method 2
np.arange(30).reshape(2,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [10]:
# Method 3
np.empty((2,3,5))

array([[[0.07072139, 0.72902613, 0.30102606, 0.17852937, 0.29223761],
        [0.9050767 , 0.52327413, 0.77688575, 0.82430772, 0.03290923],
        [0.68433149, 0.53126271, 0.40118318, 0.12979977, 0.79356757]],

       [[0.74760867, 0.57134778, 0.91224543, 0.71890306, 0.63823787],
        [0.14462357, 0.84584131, 0.44899149, 0.6808421 , 0.11948021],
        [0.50097376, 0.87840702, 0.17547447, 0.62221978, 0.82434951]]])

#### 4. Print *a*.


In [11]:
# your code here
print(a)

[[[0.07072139 0.72902613 0.30102606 0.17852937 0.29223761]
  [0.9050767  0.52327413 0.77688575 0.82430772 0.03290923]
  [0.68433149 0.53126271 0.40118318 0.12979977 0.79356757]]

 [[0.74760867 0.57134778 0.91224543 0.71890306 0.63823787]
  [0.14462357 0.84584131 0.44899149 0.6808421  0.11948021]
  [0.50097376 0.87840702 0.17547447 0.62221978 0.82434951]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [21]:
# your code here
b = np.full((5,3,2), 1)

#### 6. Print *b*.


In [22]:
# your code here
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [14]:
# your code here
print(b.size == a.size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here
# you cannot add those two matrices because they do not have the same dimensions

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [23]:
# your code here
c = b.transpose()
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [25]:
# your code/answer here
d = np.add(a,c)
d

array([[[1.07072139, 1.72902613, 1.30102606, 1.17852937, 1.29223761],
        [1.9050767 , 1.52327413, 1.77688575, 1.82430772, 1.03290923],
        [1.68433149, 1.53126271, 1.40118318, 1.12979977, 1.79356757]],

       [[1.74760867, 1.57134778, 1.91224543, 1.71890306, 1.63823787],
        [1.14462357, 1.84584131, 1.44899149, 1.6808421 , 1.11948021],
        [1.50097376, 1.87840702, 1.17547447, 1.62221978, 1.82434951]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [26]:
# your code/answer here
print(a)
print(d)

# ä yes, every value in d is on one full value grater than the equivalent value in a and why, well because we have just added to every value a +1 from the all ones matrix

[[[0.07072139 0.72902613 0.30102606 0.17852937 0.29223761]
  [0.9050767  0.52327413 0.77688575 0.82430772 0.03290923]
  [0.68433149 0.53126271 0.40118318 0.12979977 0.79356757]]

 [[0.74760867 0.57134778 0.91224543 0.71890306 0.63823787]
  [0.14462357 0.84584131 0.44899149 0.6808421  0.11948021]
  [0.50097376 0.87840702 0.17547447 0.62221978 0.82434951]]]
[[[1.07072139 1.72902613 1.30102606 1.17852937 1.29223761]
  [1.9050767  1.52327413 1.77688575 1.82430772 1.03290923]
  [1.68433149 1.53126271 1.40118318 1.12979977 1.79356757]]

 [[1.74760867 1.57134778 1.91224543 1.71890306 1.63823787]
  [1.14462357 1.84584131 1.44899149 1.6808421  1.11948021]
  [1.50097376 1.87840702 1.17547447 1.62221978 1.82434951]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [31]:
# your code here
e = np.multiply(a,c)
e

array([[[0.07072139, 0.72902613, 0.30102606, 0.17852937, 0.29223761],
        [0.9050767 , 0.52327413, 0.77688575, 0.82430772, 0.03290923],
        [0.68433149, 0.53126271, 0.40118318, 0.12979977, 0.79356757]],

       [[0.74760867, 0.57134778, 0.91224543, 0.71890306, 0.63823787],
        [0.14462357, 0.84584131, 0.44899149, 0.6808421 , 0.11948021],
        [0.50097376, 0.87840702, 0.17547447, 0.62221978, 0.82434951]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [30]:
# your code/answer here
print( e==a)
# yes it does because every value is multiplied by one (all values in c are =1) and therefor do not change their value

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


array([[[0.07072139, 0.72902613, 0.30102606, 0.17852937, 0.29223761],
        [0.9050767 , 0.52327413, 0.77688575, 0.82430772, 0.03290923],
        [0.68433149, 0.53126271, 0.40118318, 0.12979977, 0.79356757]],

       [[0.74760867, 0.57134778, 0.91224543, 0.71890306, 0.63823787],
        [0.14462357, 0.84584131, 0.44899149, 0.6808421 , 0.11948021],
        [0.50097376, 0.87840702, 0.17547447, 0.62221978, 0.82434951]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [35]:
# your code here
d_max = np.max(d)
d_mean =np.mean(d)
d_min = np.min(d)
d_mean

1.533456160549029

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [48]:
# your code here
f = np.empty((2,3,5))


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [55]:
f = []
for x in d:
    for y in x:
        for z in y:
            if z >d_min and z < d_mean:
                f += [25]
            elif z > d_mean and z < d_max:
                f += [75]
            elif z == d_mean:
                f += [50]
            elif z == d_max:
                f += [100]
            else:
                f += [0]
f = np.reshape(f, d.shape)
print(f)            

[[[ 25  75  25  25  25]
  [ 75  25  75  75   0]
  [ 75  25  25  25  75]]

 [[ 75  75 100  75  75]
  [ 25  75  25  75  25]
  [ 25  75  25  75  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [56]:
# your code here
f = []
for x in d:
    for y in x:
        for z in y:
            if z >d_min and z < d_mean:
                f += ['B']
            elif z > d_mean and z < d_max:
                f += ['D']
            elif z == d_mean:
                f += ['C']
            elif z == d_max:
                f += ['E']
            else:
                f += ['A']
f = np.reshape(f, d.shape)
print(f)            

[[['B' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'A']
  ['D' 'B' 'B' 'B' 'D']]

 [['D' 'D' 'E' 'D' 'D']
  ['B' 'D' 'B' 'D' 'B']
  ['B' 'D' 'B' 'D' 'D']]]
